name: Java CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Compile and Run Java
        run: |
          javac src/Main.java
          java src/Main.java

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t docker.io/geovanadiniz/java:${{ github.run_number }} -f dockerfile .

      - name: Push Docker image
        run: |
          docker push docker.io/geovanadiniz/java_pilha:${{ github.run_number }}
