 
name: Java CI

on:
  pull_request:
    branches: [ "qa prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
    - name: Compile and Run Java
      run: |
        javac src/Main.java
        java src/Main.java


    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: pedrom421/hello_world
        tags: ${{ GITHUB.RUN_NUMBER }}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
